apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpmetric-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpmetric
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: httpmetric
    spec:
      affinity:
        # podAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #   - labelSelector:
        #       matchExpressions:
        #         - key: a
        #           operator: In
        #           values:
        #             - b
        #     topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - http
            topologyKey: kubernetes.io/hostname
      imagePullSecrets:      
        - name: lincoln 
      containers:
        - 
          name: httpmetric
          image: linkinlxm/cncamp:prometheus_v1.0
          ports:
            - containerPort: 80
          env:
            - name: VERSION
              valueFrom: 
                configMapKeyRef:
                  key: httpmetric-env
                  name: httpmetric-env
          startupProbe:
            httpGet:
              path: /healthyz
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - ls
                - /app/http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 80
              path: /healthyz
              httpHeaders:
                - name: Custom-Headers
                  value: Awsome
            initialDelaySeconds: 3
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: 
                - echo "stoping"
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "128Mi"
              cpu: "128m"
#          dnsPolicy: ClusterFirst
#          restartPolicy: Always
#          schedulerName: default-scheduler
#          securityContext: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpmetric-env
data:
  httpmetric-env: some_test_env_version
